insert into APP_USER(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) values('admin', '21232f297a57a5a743894a0e4a801fc3', 'System', 'Admin')
insert into APP_USER(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) values('user','ee11cbb19052e40b07aac0ca060c23ee', 'General', 'User')
insert into APP_ROLE(ROLENAME) values('ROLE_ADMIN')
insert into APP_ROLE(ROLENAME) values('ROLE_USER')
insert into APP_USER_ROLE(USERNAME, ROLENAME) values('admin', 'ROLE_ADMIN')
insert into APP_USER_ROLE(USERNAME, ROLENAME) values('admin', 'ROLE_USER')
insert into APP_USER_ROLE(USERNAME, ROLENAME) values('user', 'ROLE_USER')

INSERT INTO APP (description,image,name) VALUES ('The Cloud is a place of magic and wonder.  Businesses run smoothly in the Cloud.  Developers no longer need system administrators, or food and water for that matter.  You can watch television on your tablet device from the comfort of your own sofa, without having to look up at the television.  Download the Cloud app, from the Cloud, and harness this awesome power today!','cloud.jpg','The Cloud');
INSERT INTO APP (description,image,name) VALUES ('A high-powered productivity app for high-powered sales professionals.  Track your high-powered leads, and manage your high-powered schedule.  When you are out on the town doing high-powered networking, you want to show your high-powered sales prospects that you are high-powered too.','pointing.jpg','Sales Closer');
INSERT INTO APP (description,image,name) VALUES ('This game app offers all the excitement of football (soccer), except that it''s played on a touch screen rather than your feet.  So there isn''t any of the kicking, or the running, or any of the physical exercise at all.  Other than that, it''s pretty much the same.','ball.jpg','World Tournament Football');
INSERT INTO APP (description,image,name) VALUES ('A dazzling game app, in which you connect crystals of the same color to make them go away.  It''s sort of like Tetris.  Actually, it''s sort of like the other dozen or so other games today where you connect crystals of the same color.','brilliant.jpg','Yet Another Crystal Game');
INSERT INTO APP (description,image,name) VALUES ('Sharpen your pencils, by sticking them into your phone''s Bluetooth plug and pushing a button.  This app really pushes your phone''s hardware to its limits!','pencil.jpg','Pencil Sharpener');
INSERT INTO APP (description,image,name) VALUES ('Is someone always taking your stapler?  It''s a common problem in many office spaces.  This business productivity app will help you manage your stapler at all times, so that you will never have to deal with a "case of the Mondays" again.','stapler.jpg','Stapler Tracker');
INSERT INTO APP (description,image,name) VALUES ('A fun little game app, where you throw large birds around for no apparent reason.  Why else do you think they''re so frustrated?','flamingo.jpg','Frustrated Flamingos');
INSERT INTO APP (description,image,name) VALUES ('Make free local and international calls, with video, using this app and your home Internet connection.  Better yet, make free calls using your employer''s Internet connection!','laptop.jpg','Grype Video Conferencing');
INSERT INTO APP (description,image,name) VALUES ('Read books on your computer, or on the go from your mobile device with this powerful e-reader app.  We recommend "Hibernate Search by Example", from Packt Publishing.','book.jpg','E-Book Reader');
INSERT INTO APP (description,image,name) VALUES ('This amazing app allows us to track all of your online activity.  We can figure out where you live, what you had for breakfast this morning, or what your closest secrets are.  The app also includes a web browser.','orangeswirls.jpg','Dome Web Browser');
INSERT INTO APP (description,image,name) VALUES ('Listen to your favorite songs on streaming Internet radio!  When you like a song, this app will play more songs similar to that one.  Or at least it plays more songs... to be honest, sometimes they''re not all that similar.  :(','jamming.jpg','Athena Internet Radio');
INSERT INTO APP (description,image,name) VALUES ('Do you need directions to help you reach a destination?  This GPS app will definitely produce enough turn-by-turn directions to get you there!  Eventually.','compass.jpg','Map Journey');

